### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by markov555** [adram3l3ch/fb-clone-backend#2]
Can you please provide more information about configuring .env file?

**Comment by adram3l3ch** [comment]
Pull the latest repo and execute `npm run create-env`. It will create a sample .env file for you you have to fill the values with your own , cloudinary is the cloud platform used so create an account on it for the cloud api key and secret

**Comment by adram3l3ch** [comment]
Add a .env in frontend `REACT_APP_ENV=DEVELOPMENT`
